My Project: it.braceletreader.fragments.SettingFragment Class Reference
it.braceletreader.fragments.SettingFragment Class Reference
Public Member Functions
SettingFragment (BraceletReader braceletReader)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onDestroyView ()
void update (Observable observable, Object data)
Public Member Functions inherited from it.braceletreader.fragments.MyFragment
MyFragment (int layoutID)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onTabReselected (Tab tab, FragmentTransaction ft)
void onTabSelected (Tab tab, FragmentTransaction ft)
void onTabUnselected (Tab tab, FragmentTransaction ft)
Detailed Description
Fragment that show the setting layout
Author
Lucchetti Daniele
Definition at line 38 of file SettingFragment.java.
Constructor & Destructor Documentation
it.braceletreader.fragments.SettingFragment.SettingFragment (BraceletReader braceletReader)
Costructor
Parameters
braceletReader Main class
Definition at line 58 of file SettingFragment.java.
References it.braceletreader.SharedData.getInstance().
     {
         super(R.layout.settings_tab_bracelet_reader);
         this.m_braceletReader = braceletReader;
         this.m_sharedData = SharedData.getInstance();
     }
Member Function Documentation
View it.braceletreader.fragments.SettingFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Called when the view is created
Definition at line 69 of file SettingFragment.java.
References it.braceletreader.BraceletReader.CONNECTED_BRACELETS, it.braceletreader.BraceletReader.CONNECTED_WIFI_NAME, it.braceletreader.SharedData.get(), it.braceletreader.BraceletReader.getBluetoothLeMode(), it.braceletreader.BraceletReader.pickImage(), it.braceletreader.SharedData.put(), it.braceletreader.BraceletReader.selectBracelets(), it.braceletreader.BraceletReader.SERVER_ADDRESS, it.braceletreader.BraceletReader.setBluetoothLeMode(), it.braceletreader.BraceletReader.startWifiConnection(), it.braceletreader.BraceletReader.USER_IMAGE, and it.braceletreader.BraceletReader.USERNAME.
     {
         View view = super.onCreateView(inflater, container, savedInstanceState);
         /*
          * UI inizialization
          */
         this.m_bluetoothStateTextview = (TextView) view.findViewById(R.id.bluetooth_state_textview);
         this.m_wifiStateTextview = (TextView) view.findViewById(R.id.wifi_state_textview);
         this.m_nameEdittext = (EditText) view.findViewById(R.id.name_edittext);
         this.m_serverAddressEdittext = (EditText) view.findViewById(R.id.server_address_edittext);
         this.m_imageButton = (ImageButton) view.findViewById(R.id.imageButton1);
         this.m_braceletsSelectionButton = (Button) view.findViewById(R.id.bracelet_selection_button);
         this.m_wifiSelectionButton = (Button) view.findViewById(R.id.wifi_selection_button);
         this.m_bluetoothLeSearching = (CheckBox) view.findViewById(R.id.bluetooth_le_searching_checkbox);
         /*
          * UI update
          */
         if ( this.m_sharedData.get(BraceletReader.USERNAME) != null )
         {
             this.m_nameEdittext.setText((String) this.m_sharedData.get(BraceletReader.USERNAME));
         }
         // TextChangeListener to get new username inserted
         this.m_nameEdittext.addTextChangedListener(new TextWatcher()
         {
             @Override
             public void onTextChanged( CharSequence s, int start, int before, int count )
             {
             }
             @Override
             public void beforeTextChanged( CharSequence s, int start, int count, int after )
             {
             }
             @Override
             public void afterTextChanged( Editable s )
             {
                 m_sharedData.put(BraceletReader.USERNAME, m_nameEdittext.getText().toString());
             }
         });
         // Construction the string for Bluetooth state
         List<BluetoothDevice> devices = (List<BluetoothDevice>) this.m_sharedData.get(BraceletReader.CONNECTED_BRACELETS);
         String string = "";
         if ( devices != null && devices.size() > 0 )
         {
             for ( int i = 0; i < devices.size() - 1; i++ )
             {
                 string += devices.get(i).getName() + "; ";
             }
             string += devices.get(devices.size() - 1).getName();
         }
         setTextViewText(this.m_bluetoothStateTextview, string);
         setTextViewText(this.m_wifiStateTextview, (String) this.m_sharedData.get(BraceletReader.CONNECTED_WIFI_NAME));
         // Load server address
         if ( this.m_sharedData.get(BraceletReader.SERVER_ADDRESS) != null )
         {
             this.m_serverAddressEdittext.setText((String) this.m_sharedData.get(BraceletReader.SERVER_ADDRESS));
         }
         // OnClickListeren to pick image for user image
         this.m_imageButton.setOnClickListener(new OnClickListener()
         {
             @Override
             public void onClick( View v )
             {
                 m_braceletReader.pickImage();
             }
         });
         // Load user image
         Bitmap image = (Bitmap) this.m_sharedData.get(BraceletReader.USER_IMAGE);
         if ( image != null )
         {
             this.m_imageButton.setImageBitmap(image);
         }
         // OnClickListener to select bracelets
         this.m_braceletsSelectionButton.setOnClickListener(new OnClickListener()
         {
             @Override
             public void onClick( View v )
             {
                 m_braceletReader.selectBracelets();
             }
         });
         // OnClickListener to select Wifi network
         this.m_wifiSelectionButton.setOnClickListener(new OnClickListener()
         {
             @Override
             public void onClick( View v )
             {
                 m_braceletReader.startWifiConnection();
             }
         });
         // Load type of Bluetooth used
         this.m_bluetoothLeSearching.setChecked(this.m_braceletReader.getBluetoothLeMode());
         // OnCheckedChangeListener to get checked update
         this.m_bluetoothLeSearching.setOnCheckedChangeListener(new OnCheckedChangeListener()
         {
             @Override
             public void onCheckedChanged( CompoundButton buttonView, boolean isChecked )
             {
                 m_braceletReader.setBluetoothLeMode(isChecked);
             }
         });
         // Implementation of hander
         this.m_handler = new Handler(Looper.getMainLooper())
         {
             @Override
             public void handleMessage( Message message )
             {
                 // Update user image
                 m_imageButton.setImageBitmap((Bitmap) m_sharedData.get(BraceletReader.USER_IMAGE));
                 // Update of Bluetooth state TextView
                 List<BluetoothDevice> devices = (List<BluetoothDevice>) m_sharedData.get(BraceletReader.CONNECTED_BRACELETS);
                 String string = "";
                 if ( devices != null && devices.size() > 0 )
                 {
                     for ( int i = 0; i < devices.size() - 1; i++ )
                     {
                         string += devices.get(i).getName() + "; ";
                     }
                     string += devices.get(devices.size() - 1).getName();
                 }
                 setTextViewText(m_bluetoothStateTextview, string);
                 // Update of Wifi state TextView
                 setTextViewText(m_wifiStateTextview, (String) m_sharedData.get(BraceletReader.CONNECTED_WIFI_NAME));
             }
         };
         /* Register observer to update the UI on data changing */
         this.m_sharedData.addObserver(this);
         return view;
     }
void it.braceletreader.fragments.SettingFragment.onDestroyView ()
Called when the view is deleted
Definition at line 223 of file SettingFragment.java.
     {
         /* Unregister observer */
         this.m_sharedData.deleteObserver(this);
         super.onDestroyView();
     }
void it.braceletreader.fragments.SettingFragment.update (Observable observable, Object data)
Method called on data changing to update UI
Definition at line 251 of file SettingFragment.java.
     {
         this.m_handler.obtainMessage().sendToTarget();
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/fragments/SettingFragment.java