My Project: it.braceletreader.BraceletReader Class Reference
it.braceletreader.BraceletReader Class Reference
Classes
class MyServiceConnection
Public Member Functions
void onActivityResult (int request, int result, Intent intent)
void setBluetoothLeMode (boolean enabled)
boolean getBluetoothLeMode ()
void selectBracelets ()
void showAlertDialog ()
void startWifiConnection ()
void onClick (DialogInterface dialog, int which, boolean isChecked)
void onClick (DialogInterface dialog, int which)
void createBluetoothConnections (List< BluetoothDevice > devices)
void leScanStopped (Set< BluetoothDevice > foundDevices)
void deviceFound (BluetoothDevice device, int rssi, byte[] scanRecord)
void notifyListenerStateChanged (int id, int state)
void updateUI (Object data)
void pickImage ()
void setUserImage (Uri uri)
void serviceStarted (BluetoothManager bluetoothManager)
void serviceStopped ()
Static Public Attributes
static final int REQUEST_PICK_IMAGE = 0
ID for image picking request.
static final String USERNAME = "username"
Key to access to the value in SharedData containing the username.
static final String USER_IMAGE = "user_image"
Key to access to the value in SharedData containing the user's image.
static final String CONNECTED_BRACELETS = "connected_bracelet"
Key to access to the value in SharedData containing the list of connected bracelet.
static final String CONNECTED_WIFI_NAME = "connected_wifi_name"
Key to access to the value in SharedData containing the connected wifi's name.
static final String SERVER_ADDRESS = "server_address"
Key to access to the value in SharedData containing the server address what send data.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onResume ()
void onPause ()
void onStop ()
void onDestroy ()
Detailed Description
Main class. Activity to launch application
Author
Lucchetti Daniele
Definition at line 52 of file BraceletReader.java.
Member Function Documentation
void it.braceletreader.BraceletReader.createBluetoothConnections (List< BluetoothDevice > devices)
Start a new connection with the specified device
Definition at line 366 of file BraceletReader.java.
References it.braceletreader.listeners.BraceletListener.alt(), it.braceletreader.BraceletReader.CONNECTED_BRACELETS, and it.braceletreader.SharedData.put().
Referenced by it.braceletreader.BraceletReader.onClick().
     {
         // If the BraceletListeners are running, they are stopped
         if ( this.m_braceletListener != null )
         {
             for ( int i = 0; i < this.m_braceletListener.length; i++ )
             {
                 this.m_braceletListener[i].alt();
             }
         }
         // Than they are instanced again
         this.m_braceletListener = new BraceletListener[devices.size()];
         if ( !this.m_bluetoothLeMode )
         {
             // If the user want using a Bluetooth version less than 4.0
             for ( int i = 0; i < devices.size(); i++ )
             {
                 this.m_braceletListener[i] = new BluetoothBraceletListener(i, this, this.m_dataManager, devices.get(i), UUID.fromString(getString(R.string.UUID)));
                 this.m_braceletListener[i].start();
             }
         } else
         {
             // If the user want using Bluetooth LE devices
             for ( int i = 0; i < devices.size(); i++ )
             {
                 // It is created the list of Services that we want activing
                 List<BluetoothLeService> services = new ArrayList<BluetoothLeService>();
                 services.add(new SensorTagAccelerometer());
                 // services.add(new SensorTagGyroscope());
                 this.m_braceletListener[i] = new BluetoothLeBraceletListener(i, this, this.m_dataManager, devices.get(i), services);
                 this.m_braceletListener[i].start();
             }
         }
         this.m_sharedData.put(BraceletReader.CONNECTED_BRACELETS, new ArrayList<BluetoothDevice>());
     }
void it.braceletreader.BraceletReader.deviceFound (BluetoothDevice device, int rssi, byte[] scanRecord)
Called when a device LE is found
Implements it.braceletreader.managers.BluetoothLeCallbacks.
Definition at line 419 of file BraceletReader.java.
     {
     }
boolean it.braceletreader.BraceletReader.getBluetoothLeMode ()
Return true if they will searched Bluetooth LE devices
Definition at line 243 of file BraceletReader.java.
Referenced by it.braceletreader.fragments.SettingFragment.onCreateView().
     {
         return this.m_bluetoothLeMode;
     }
void it.braceletreader.BraceletReader.leScanStopped (Set< BluetoothDevice > foundDevices)
Called when the LE scan is finished
Implements it.braceletreader.managers.BluetoothLeCallbacks.
Definition at line 407 of file BraceletReader.java.
References it.braceletreader.BraceletReader.showAlertDialog().
     {
         // Bluetooth LE scan is finished, so the found devices are shown in the dialog
         this.m_foundDevices = new BluetoothDevice[foundDevices.size()];
         foundDevices.toArray(this.m_foundDevices);
         showAlertDialog();
     }
void it.braceletreader.BraceletReader.notifyListenerStateChanged (int id, int state)
Notify errors or state changing by BraceletListener
Parameters
id The BraceletListener id
state An integer representing the new state of listener
Definition at line 429 of file BraceletReader.java.
References it.braceletreader.listeners.BraceletListener.alt(), it.braceletreader.BraceletReader.CONNECTED_BRACELETS, it.braceletreader.listeners.BraceletListener.CONNECTION_ESTABLISHED, it.braceletreader.listeners.BraceletListener.ERROR_CREATING_CONNECTION, it.braceletreader.SharedData.get(), it.braceletreader.listeners.BraceletListener.getDevice(), and it.braceletreader.SharedData.put().
     {
         switch ( state )
         {
         case BraceletListener.CONNECTION_ESTABLISHED:
             // The connection was successful, so the list of connected devices is update
             List<BluetoothDevice> devices = (List<BluetoothDevice>) this.m_sharedData.get(BraceletReader.CONNECTED_BRACELETS);
             devices.add(this.m_braceletListener[id].getDevice());
             this.m_sharedData.put(BraceletReader.CONNECTED_BRACELETS, devices);
             break;
         case BraceletListener.ERROR_CREATING_CONNECTION:
             // Connection error when listener was trying to connect, so a message is shown to user
             this.m_braceletListener[id].alt();
             Message message = this.m_handler.obtainMessage();
             message.arg1 = R.string.error_not_connected;
             message.obj = this.m_braceletListener[id].getDevice().getName();
             message.sendToTarget();
             break;
         }
     }
void it.braceletreader.BraceletReader.onActivityResult (int request, int result, Intent intent)
Method to give information about started activity
Definition at line 215 of file BraceletReader.java.
References it.braceletreader.BraceletReader.setUserImage().
     {
         switch ( request )
         {
         case (REQUEST_PICK_IMAGE):
             // Activity to pick an image as user image
             if ( result == Activity.RESULT_OK )
             {
                 Uri uri = intent.getData();
                 setUserImage(uri);
             }
             break;
         }
     }
void it.braceletreader.BraceletReader.onClick (DialogInterface dialog, int which, boolean isChecked)
Called when the items are clicked in the dialog
Definition at line 317 of file BraceletReader.java.
Referenced by it.braceletreader.BraceletReader.serviceStarted().
     {
         // If device is selected, it is add to list, else it is removed
         if ( isChecked )
         {
             this.m_selectedDevices.add(this.m_foundDevices[which]);
         } else
         {
             this.m_selectedDevices.remove(Integer.valueOf(which));
         }
     }
void it.braceletreader.BraceletReader.onClick (DialogInterface dialog, int which)
Called when the buttons are clicked in the dialog
Definition at line 333 of file BraceletReader.java.
References it.braceletreader.BraceletReader.createBluetoothConnections(), it.braceletreader.managers.BluetoothManager.showSettings(), and it.braceletreader.managers.BluetoothManager.startLeScan().
     {
         if ( which == DialogInterface.BUTTON_POSITIVE )
         {
             // If the number of selected devices is less than eight, the connections are created. Else a message is shown to user
             if ( this.m_selectedDevices.size() < 8 )
             {
                 createBluetoothConnections(this.m_selectedDevices);
             } else
             {
                 Message message = this.m_handler.obtainMessage();
                 message.arg1 = R.string.error_max_connection_possible;
                 message.sendToTarget();
             }
         } else
         {
             // If is clicked on negative button, it means that the wanted devices was not in the list
             if ( !this.m_bluetoothLeMode )
             {
                 // Bluetooth setting is opened to search and pair other devices
                 this.m_bluetoothManager.showSettings();
             } else
             {
                 // If the interesting LE devices aren't found in 1 seconds another search in 5 seconds is made
                 this.m_bluetoothManager.startLeScan(this, 5000);
             }
         }
         this.m_selectedDevices = null;
     }
void it.braceletreader.BraceletReader.onCreate (Bundle savedInstanceState) protected
Method called when the app is created
Definition at line 85 of file BraceletReader.java.
References it.braceletreader.SharedData.getInstance(), and it.braceletreader.BraceletReader.SERVER_ADDRESS.
     {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_bracelet_reader);
         /*
          * Structure initialization
          */
         this.m_dataManager = new DataManager<Data>();
         this.m_sharedData = SharedData.getInstance();
         /*
          * UI initialization
          */
         ActionBar bar = getActionBar();
         /* Tabs creating */
         bar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
         this.m_mainFragment = new MainFragment();
         this.m_settingFragment = new SettingFragment(this);
         bar.addTab(bar.newTab().setText(getString(R.string.tab1_name)).setTabListener(this.m_mainFragment));
         bar.addTab(bar.newTab().setText(getString(R.string.tab2_name)).setTabListener(this.m_settingFragment));
         /* Handler definition */
         this.m_handler = new Handler(Looper.getMainLooper())
         {
             @Override
             public void handleMessage( Message inputMessage )
             {
                 /* The Message must contain an ID of a string to stamp and can contain a String in obj attribute as additional information */
                 String text = getString(inputMessage.arg1);
                 if ( inputMessage.obj != null )
                 {
                     text += " " + inputMessage.obj;
                 }
                 Toast.makeText(getApplicationContext(), text, Toast.LENGTH_LONG).show();
             }
         };
         /*
          * WiFi initialization
          */
         this.m_wifiManager = (WifiManager) getSystemService(WIFI_SERVICE);
         this.m_connectivityManager = (ConnectivityManager) getSystemService(CONNECTIVITY_SERVICE);
         this.m_initialWifiState = this.m_wifiManager.isWifiEnabled();
         // Initialization of server address (//TODO this line must remove)
         this.m_sharedData.put(BraceletReader.SERVER_ADDRESS, getString(R.string.server_URL));
     }
void it.braceletreader.BraceletReader.onDestroy () protected
Method called when the app is destroyed
Definition at line 181 of file BraceletReader.java.
References it.braceletreader.listeners.BraceletListener.alt(), it.braceletreader.Sender.alt(), and it.braceletreader.managers.BluetoothManager.disable().
     {
         // All thread are stopped
         for ( int i = 0; i < this.m_braceletListener.length; i++ )
         {
             if ( this.m_braceletListener[i] != null )
             {
                 this.m_braceletListener[i].alt();
             }
         }
         if ( this.m_sender != null )
         {
             this.m_sender.alt();
         }
         // Turn off Bluetooth and Wifi if they were turned off at the app start
         if ( !this.m_initialBluetoothState )
         {
             this.m_bluetoothManager.disable();
         }
         if ( !this.m_initialWifiState )
         {
             this.m_wifiManager.setWifiEnabled(false);
         }
         // Unbind and stop Bluetooth service
         unbindService(this.m_serviceConnection);
         stopService(new Intent(this, BluetoothManager.class));
         super.onDestroy();
     }
void it.braceletreader.BraceletReader.onPause () protected
Method called when the app is paused
Definition at line 163 of file BraceletReader.java.
     {
         super.onPause();
     }
void it.braceletreader.BraceletReader.onResume () protected
Method called when the app is resumed
Definition at line 138 of file BraceletReader.java.
     {
         /*
          * Bluetooth initialization
          */
         if ( this.m_bluetoothManager == null )
         {
             // Create a ServiceConnection object and bind the BLuetooth service. ServiceConnection give us information about binding
             this.m_serviceConnection = new MyServiceConnection();
             bindService(new Intent(this, BluetoothManager.class), this.m_serviceConnection, Context.BIND_AUTO_CREATE);
         }
         // Enabling wifi
         if ( !this.m_wifiManager.isWifiEnabled() )
         {
             this.m_wifiManager.setWifiEnabled(true);
         }
         super.onResume();
     }
void it.braceletreader.BraceletReader.onStop () protected
Method called when the app is stopped
Definition at line 172 of file BraceletReader.java.
     {
         super.onStop();
     }
void it.braceletreader.BraceletReader.pickImage ()
Start activity to pick an image
Definition at line 463 of file BraceletReader.java.
Referenced by it.braceletreader.fragments.SettingFragment.onCreateView().
     {
         Intent intent = new Intent(Intent.ACTION_PICK);
         intent.setType("image/*");
         startActivityForResult(intent, REQUEST_PICK_IMAGE);
     }
void it.braceletreader.BraceletReader.selectBracelets ()
Show Bluetooth binding device in case it's already paired or start Bluetooth LE device scan
Definition at line 251 of file BraceletReader.java.
References it.braceletreader.managers.BluetoothManager.getBondedDevices(), it.braceletreader.BraceletReader.showAlertDialog(), and it.braceletreader.managers.BluetoothManager.startLeScan().
Referenced by it.braceletreader.fragments.SettingFragment.onCreateView().
     {
         if ( !this.m_bluetoothLeMode )
         {
             Set<BluetoothDevice> bondedDevices = this.m_bluetoothManager.getBondedDevices();
             this.m_foundDevices = new BluetoothDevice[bondedDevices.size()];
             bondedDevices.toArray(this.m_foundDevices);
             showAlertDialog();
         } else
         {
             this.m_bluetoothManager.startLeScan(this, 1000);
         }
     }
void it.braceletreader.BraceletReader.serviceStarted (BluetoothManager bluetoothManager)
Signal that the service in started
Parameters
bluetoothManager The instance of BluetoothManager by the Service
Definition at line 494 of file BraceletReader.java.
References it.braceletreader.managers.BluetoothManager.enable(), it.braceletreader.managers.BluetoothManager.isEnabled(), it.braceletreader.managers.BluetoothManager.isSupported(), and it.braceletreader.BraceletReader.onClick().
     {
         // The BLuetooth service is started, so it is verified that Bluetooth is supported. In this case, the app is closed
         this.m_bluetoothManager = bluetoothManager;
         if ( !this.m_bluetoothManager.isSupported() )
         {
             /* Error message */
             AlertDialog.Builder builder = new AlertDialog.Builder(getApplicationContext());
             builder.setCancelable(false);
             builder.setMessage(R.string.error_bluetooth_not_supported);
             builder.setPositiveButton(R.string.closing_message, new DialogInterface.OnClickListener()
             {
                 @Override
                 public void onClick( DialogInterface arg0, int arg1 )
                 {
                     finish();
                 }
             });
         }
         this.m_initialBluetoothState = this.m_bluetoothManager.isEnabled();
         // Enablig Bluetooth
         if ( !this.m_bluetoothManager.isEnabled() )
         {
             this.m_bluetoothManager.enable();
         }
     }
void it.braceletreader.BraceletReader.serviceStopped ()
Signal that the service is stopped
Definition at line 527 of file BraceletReader.java.
     {
         this.m_bluetoothManager = null;
     }
void it.braceletreader.BraceletReader.setBluetoothLeMode (boolean enabled)
Set the type of Bluetooth devices to find
Parameters
enabled If true, Bluetooth LE are used; traditional Bluetooth otherwise
Definition at line 235 of file BraceletReader.java.
Referenced by it.braceletreader.fragments.SettingFragment.onCreateView().
     {
         this.m_bluetoothLeMode = enabled;
     }
void it.braceletreader.BraceletReader.setUserImage (Uri uri)
Resize and set the new user image
Definition at line 473 of file BraceletReader.java.
References it.braceletreader.SharedData.put(), and it.braceletreader.BraceletReader.USER_IMAGE.
Referenced by it.braceletreader.BraceletReader.onActivityResult().
     {
         /* Take the image */
         String[] filePathColumn = { MediaStore.Images.Media.DATA };
         Cursor cursor = getContentResolver().query(uri, filePathColumn, null, null, null);
         cursor.moveToFirst();
         String filePath = cursor.getString(0);
         cursor.close();
         Bitmap image = BitmapFactory.decodeFile(filePath);
         /* Resize image */
         Bitmap scaledBitmap = Bitmap.createScaledBitmap(image, 130, 130, true);
         this.m_sharedData.put(BraceletReader.USER_IMAGE, scaledBitmap);
     }
void it.braceletreader.BraceletReader.showAlertDialog ()
Show an alert dialog with a multi-choice list of devices
Definition at line 268 of file BraceletReader.java.
Referenced by it.braceletreader.BraceletReader.leScanStopped(), and it.braceletreader.BraceletReader.selectBracelets().
     {
         int size = this.m_foundDevices.length;
         this.m_selectedDevices = new ArrayList<BluetoothDevice>();
         /* Construct an array containing names of Blueooth devices */
         CharSequence[] names = new CharSequence[size];
         for ( int i = 0; i < size; i++ )
         {
             names[i] = this.m_foundDevices[i].getName();
         }
         AlertDialog.Builder builder = new AlertDialog.Builder(this);
         builder.setTitle(R.string.dialog_title);
         builder.setMultiChoiceItems(names, new boolean[size], this);
         builder.setPositiveButton(R.string.ok, this); // If positive button is pressed, a connection is attempted with selected device
         builder.setNegativeButton(R.string.search_other_device, this); // If positive button is pressed, Bluetooth settings are opened to paired other devices
         builder.create().show();
     }
void it.braceletreader.BraceletReader.startWifiConnection ()
Connect to a Wifi network and verify Internet connection
Definition at line 289 of file BraceletReader.java.
References it.braceletreader.SharedData.get(), and it.braceletreader.BraceletReader.SERVER_ADDRESS.
Referenced by it.braceletreader.fragments.SettingFragment.onCreateView().
     {
         if ( this.m_braceletListener != null && this.m_sender == null )
         {
             if ( !this.m_wifiManager.isWifiEnabled() )
             {
                 this.m_wifiManager.setWifiEnabled(true);
             }
             /* Check Network and start thread to send data to server */
             NetworkInfo networkInfo = this.m_connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
             if ( networkInfo != null && networkInfo.isConnected() )
             {
                 this.m_sender = new Sender(this.m_dataManager, (String) this.m_sharedData.get(BraceletReader.SERVER_ADDRESS));
                 this.m_sender.start();
             } else
             {
                 // Wifi settings are opened if device is not connected to network
                 Intent intent = new Intent(Settings.ACTION_WIFI_SETTINGS);
                 startActivity(intent);
             }
         }
     }
void it.braceletreader.BraceletReader.updateUI (Object data)
Update the UI
Parameters
data A JSON string representing the data to show
Definition at line 455 of file BraceletReader.java.
References it.braceletreader.fragments.MainFragment.updateUI().
Referenced by it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_mainFragment.updateUI(data);
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/BraceletReader.java