My Project: it.braceletreader.managers.BluetoothManager Class Reference
it.braceletreader.managers.BluetoothManager Class Reference
Classes
class MyBinder
Public Member Functions
BluetoothManager ()
int onStartCommand (Intent intent, int flags, int startId)
boolean isSupported ()
void enable ()
void disable ()
boolean isEnabled ()
void showSettings ()
Set< BluetoothDevice > getBondedDevices ()
void startLeScan (final BluetoothLeCallbacks callback, int timeout)
void stopLeScan ()
void onLeScan (BluetoothDevice device, int rssi, byte[] scanRecord)
IBinder onBind (Intent intent)
Detailed Description
Class that manage Bluetooth. First to be used, you need starting it as Service
Author
Lucchetti Daniele
Definition at line 23 of file BluetoothManager.java.
Constructor & Destructor Documentation
it.braceletreader.managers.BluetoothManager.BluetoothManager ()
Constructor
Definition at line 33 of file BluetoothManager.java.
     {
         super();
         this.m_bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
         this.m_binder = new MyBinder();
     }
Member Function Documentation
void it.braceletreader.managers.BluetoothManager.disable ()
Disable Bluetooth
Definition at line 71 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.onDestroy().
     {
         this.m_bluetoothAdapter.disable();
     }
void it.braceletreader.managers.BluetoothManager.enable ()
Enable Bluetooth
Definition at line 60 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.serviceStarted().
     {
         // Start activity to turn on Bluetooth
         Intent intent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
         intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
         startActivity(intent);
     }
Set<BluetoothDevice> it.braceletreader.managers.BluetoothManager.getBondedDevices ()
Return the paired Bluetooth device
Definition at line 98 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.selectBracelets().
     {
         return this.m_bluetoothAdapter.getBondedDevices();
     }
boolean it.braceletreader.managers.BluetoothManager.isEnabled ()
Return if Bluetooth is enabled
Definition at line 79 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.serviceStarted().
     {
         return this.m_bluetoothAdapter.isEnabled();
     }
boolean it.braceletreader.managers.BluetoothManager.isSupported ()
Return if Bluetooth is supported
Definition at line 52 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.serviceStarted().
     {
         return this.m_bluetoothAdapter != null;
     }
IBinder it.braceletreader.managers.BluetoothManager.onBind (Intent intent)
Return the IBinder used to communicate to the Service launcher
Definition at line 156 of file BluetoothManager.java.
     {
         return this.m_binder;
     }
void it.braceletreader.managers.BluetoothManager.onLeScan (BluetoothDevice device, int rssi, byte[] scanRecord)
Callback for devices LE found
Definition at line 145 of file BluetoothManager.java.
References it.braceletreader.managers.BluetoothLeCallbacks.deviceFound().
     {
         // The device is added to the list of found devices and it is notified to callback
         this.m_foundDevices.add(device);
         this.m_callback.deviceFound(device, rssi, scanRecord);
     }
int it.braceletreader.managers.BluetoothManager.onStartCommand (Intent intent, int flags, int startId)
Called when the Service is called
Definition at line 44 of file BluetoothManager.java.
     {
         return START_NOT_STICKY;
     }
void it.braceletreader.managers.BluetoothManager.showSettings ()
Open the Bluetooth setting on the screen
Definition at line 87 of file BluetoothManager.java.
Referenced by it.braceletreader.BraceletReader.onClick().
     {
         // Start the activity to show settings
         Intent intent = new Intent(Settings.ACTION_BLUETOOTH_SETTINGS);
         intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
         startActivity(intent);
     }
void it.braceletreader.managers.BluetoothManager.startLeScan (final BluetoothLeCallbacks callback, int timeout)
Start Bluetooth Low Energy scanning
Parameters
callback Who manages the found devices
timeout Indicates when stopping scan automatically is milliseconds
Definition at line 109 of file BluetoothManager.java.
References it.braceletreader.managers.BluetoothManager.stopLeScan().
Referenced by it.braceletreader.BraceletReader.onClick(), and it.braceletreader.BraceletReader.selectBracelets().
     {
         this.m_callback = callback;
         this.m_foundDevices = new HashSet<BluetoothDevice>();
         // Create an Handler that will run after timeout milliseconds to stop scanning
         Handler handler = new Handler();
         handler.postDelayed(new Runnable()
         {
             @Override
             public void run()
             {
                 // Le scan is stopped
                 stopLeScan();
             }
         }, timeout);
         // Le scan is started
         this.m_bluetoothAdapter.startLeScan(this);
     }
void it.braceletreader.managers.BluetoothManager.stopLeScan ()
Stop Bluetooth Low Energy scanning
Definition at line 132 of file BluetoothManager.java.
References it.braceletreader.managers.BluetoothLeCallbacks.leScanStopped().
Referenced by it.braceletreader.managers.BluetoothManager.startLeScan().
     {
         // Le scan is stopped and it is notified to callback
         this.m_bluetoothAdapter.stopLeScan(this);
         this.m_callback.leScanStopped(this.m_foundDevices);
         this.m_foundDevices = null;
         this.m_callback = null;
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/managers/BluetoothManager.java