My Project: it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback Class Reference
it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback Class Reference
Public Member Functions
void onConnectionStateChange (BluetoothGatt gatt, int status, int newState)
void onServicesDiscovered (BluetoothGatt gatt, int status)
void onCharacteristicWrite (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)
void onCharacteristicRead (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)
void onDescriptorWrite (BluetoothGatt gatt, BluetoothGattDescriptor descriptor, int status)
void onCharacteristicChanged (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic)
Detailed Description
My implementation of BluetoothGattCallback to manage callbacks by LE device
Author
Lucchetti Daniele
Definition at line 61 of file BluetoothLeBraceletListener.java.
Member Function Documentation
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic)
Called when the value of Services enabled changing
Definition at line 156 of file BluetoothLeBraceletListener.java.
References it.braceletreader.listeners.BluetoothLeService.getUUIDData(), it.braceletreader.listeners.BraceletListener.m_braceletReader, it.braceletreader.listeners.BraceletListener.m_dataManager, it.braceletreader.Data.setTimestamp(), it.braceletreader.Data.setType(), it.braceletreader.Data.setX(), it.braceletreader.Data.setY(), it.braceletreader.Data.setZ(), and it.braceletreader.BraceletReader.updateUI().
         {
             Integer x = characteristic.getIntValue(BluetoothGattCharacteristic.FORMAT_SINT8, 0);
             Integer y = characteristic.getIntValue(BluetoothGattCharacteristic.FORMAT_SINT8, 1);
             Integer z = characteristic.getIntValue(BluetoothGattCharacteristic.FORMAT_SINT8, 2) * -1;
             final double scaledX = x / 64.0;
             final double scaledY = y / 64.0;
             final double scaledZ = z / 64.0;
             Data data = new Data();
             data.setTimestamp(System.currentTimeMillis());
             int i = 0;
             BluetoothLeService service;
             while ( i < m_services.size() )
             {
                 service = m_services.get(i);
                 if ( characteristic.getUuid().equals(service.getUUIDData()) )
                 {
                     data.setType(service.toString());
                     break;
                 }
                 i++;
             }
             data.setX(scaledX);
             data.setY(scaledY);
             data.setZ(scaledZ);
             m_braceletReader.updateUI(data); // To update the UI
             m_dataManager.add(data);
         }
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicRead (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)
Called when a characteristic is read
Definition at line 121 of file BluetoothLeBraceletListener.java.
         {
             if ( this.m_iterator.hasNext() )
             {
                 // If there is an other characteristic to read, it will be done
                 BluetoothLeService service = this.m_iterator.next();
                 readCharacteristic(gatt, service);
             } else
             {
                 // Otherwise the list of service is scanned from the beginning
                 this.m_iterator = m_services.iterator();
                 BluetoothLeService service = this.m_iterator.next();
                 // Enabling of notification of first sensor
                 enablingNotifications(gatt, service);
             }
         }
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicWrite (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)
Called when a characteristic is written
Definition at line 100 of file BluetoothLeBraceletListener.java.
         {
             if ( this.m_iterator.hasNext() )
             {
                 // If there is an other sensor to active, it will be turned on
                 BluetoothLeService currentService = this.m_iterator.next();
                 writeConfigurationCharacteristic(gatt, currentService);
             } else
             {
                 // Otherwise the list of service is scanned from the beginning
                 this.m_iterator = m_services.iterator();
                 BluetoothLeService service = this.m_iterator.next();
                 // Read characteristic of first Service
                 readCharacteristic(gatt, service);
             }
         }
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onConnectionStateChange (BluetoothGatt gatt, int status, int newState)
Called when the connection state change
Definition at line 69 of file BluetoothLeBraceletListener.java.
         {
             if ( status == BluetoothGatt.GATT_SUCCESS && newState == BluetoothGatt.STATE_CONNECTED )
             {
                 // If the device is connected, the Services are loaded
                 gatt.discoverServices();
             } else if ( status != BluetoothGatt.GATT_SUCCESS )
             {
                 gatt.disconnect();
             }
         }
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onDescriptorWrite (BluetoothGatt gatt, BluetoothGattDescriptor descriptor, int status)
Called when a descriptor is written
Definition at line 142 of file BluetoothLeBraceletListener.java.
         {
             if ( this.m_iterator.hasNext() )
             {
                 // Until there are Services, notifications are enabled
                 BluetoothLeService service = this.m_iterator.next();
                 enablingNotifications(gatt, service);
             }
         }
void it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onServicesDiscovered (BluetoothGatt gatt, int status)
Called when the Services are loaded
Definition at line 85 of file BluetoothLeBraceletListener.java.
         {
             this.m_iterator = m_services.iterator();
             if ( this.m_iterator.hasNext() )
             {
                 BluetoothLeService currentService = this.m_iterator.next();
                 /* Turn on first sensor */
                 writeConfigurationCharacteristic(gatt, currentService);
             }
         }
The documentation for this class was generated from the following file:
src/it/braceletreader/listeners/BluetoothLeBraceletListener.java