My Project: it.braceletreader.Data Class Reference
it.braceletreader.Data Class Reference
Public Member Functions
Data ()
Data (String type, long timestamp, double x, double y, double z)
String getType ()
void setType (String type)
long getTimestamp ()
void setTimestamp (long timestamp)
double getX ()
void setX (double x)
double getY ()
void setY (double y)
double getZ ()
void setZ (double z)
String toString ()
Detailed Description
A simple structure to contain a single data
Author
Lucchetti Daniele
Definition at line 10 of file Data.java.
Constructor & Destructor Documentation
it.braceletreader.Data.Data ()
Constructor
Definition at line 21 of file Data.java.
     {
     }
it.braceletreader.Data.Data (String type, long timestamp, double x, double y, double z)
Constructor
Parameters
type Type of data
timestamp Time of detection
x X-axis value
y Y-axis value
z Z-axis value
Definition at line 35 of file Data.java.
References it.braceletreader.Data.setTimestamp(), it.braceletreader.Data.setType(), it.braceletreader.Data.setX(), it.braceletreader.Data.setY(), and it.braceletreader.Data.setZ().
     {
         this.setType(type);
         this.setTimestamp(timestamp);
         this.setX(x);
         this.setY(y);
         this.setZ(z);
     }
Member Function Documentation
long it.braceletreader.Data.getTimestamp ()
Return time of detection
Returns
Time
Definition at line 69 of file Data.java.
     {
         return m_timestamp;
     }
String it.braceletreader.Data.getType ()
Return type of containing data
Returns
Type
Definition at line 49 of file Data.java.
Referenced by it.braceletreader.fragments.MainFragment.onCreate().
     {
         return m_type;
     }
double it.braceletreader.Data.getX ()
Return x-axis value
Returns
x-axis value
Definition at line 89 of file Data.java.
Referenced by it.braceletreader.fragments.MainFragment.onCreate().
     {
         return m_x;
     }
double it.braceletreader.Data.getY ()
Return y-axis value
Returns
y-axis value
Definition at line 109 of file Data.java.
Referenced by it.braceletreader.fragments.MainFragment.onCreate().
     {
         return m_y;
     }
double it.braceletreader.Data.getZ ()
Return z-axis value
Returns
z-axis value
Definition at line 129 of file Data.java.
Referenced by it.braceletreader.fragments.MainFragment.onCreate().
     {
         return m_z;
     }
void it.braceletreader.Data.setTimestamp (long timestamp)
Set the time of detection
Parameters
timestamp
Definition at line 79 of file Data.java.
Referenced by it.braceletreader.Data.Data(), and it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_timestamp = timestamp;
     }
void it.braceletreader.Data.setType (String type)
Set type of data
Parameters
type Type
Definition at line 59 of file Data.java.
Referenced by it.braceletreader.Data.Data(), and it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_type = type;
     }
void it.braceletreader.Data.setX (double x)
Set the x-axis value
Parameters
x x-axis value
Definition at line 99 of file Data.java.
Referenced by it.braceletreader.Data.Data(), and it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_x = x;
     }
void it.braceletreader.Data.setY (double y)
Set the y-axis value
Parameters
y y-axis value
Definition at line 119 of file Data.java.
Referenced by it.braceletreader.Data.Data(), and it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_y = y;
     }
void it.braceletreader.Data.setZ (double z)
Set the z-axis value
Parameters
z z-axis value
Definition at line 139 of file Data.java.
Referenced by it.braceletreader.Data.Data(), and it.braceletreader.listeners.BluetoothLeBraceletListener.MyBluetoothGattCallback.onCharacteristicChanged().
     {
         this.m_z = z;
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/Data.java