My Project: it.braceletreader.fragments.MainFragment Class Reference
it.braceletreader.fragments.MainFragment Class Reference
Public Member Functions
MainFragment ()
void onCreate (Bundle savedInstanceState)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onDestroyView ()
void updateUI (Object data)
void update (Observable observable, Object data)
Public Member Functions inherited from it.braceletreader.fragments.MyFragment
MyFragment (int layoutID)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onTabReselected (Tab tab, FragmentTransaction ft)
void onTabSelected (Tab tab, FragmentTransaction ft)
void onTabUnselected (Tab tab, FragmentTransaction ft)
Detailed Description
Fragment that show the main layout
Author
Lucchetti Daniele
Definition at line 29 of file MainFragment.java.
Constructor & Destructor Documentation
it.braceletreader.fragments.MainFragment.MainFragment ()
Costructor
Definition at line 46 of file MainFragment.java.
References it.braceletreader.SharedData.getInstance().
     {
         super(R.layout.main_tab_bracelet_reader);
         this.m_sharedData = SharedData.getInstance();
     }
Member Function Documentation
void it.braceletreader.fragments.MainFragment.onCreate (Bundle savedInstanceState)
Called when the fragment is created
Definition at line 56 of file MainFragment.java.
References it.braceletreader.Data.getType(), it.braceletreader.Data.getX(), it.braceletreader.Data.getY(), and it.braceletreader.Data.getZ().
     {
         super.onCreate(savedInstanceState);
         /*
          * The Handler update the UI when it receives a message
          */
         this.m_handler = new Handler(Looper.getMainLooper())
         {
             @Override
             public void handleMessage( Message inputMessage )
             {
                 Data data = (Data) inputMessage.obj;
                 // Check type of data
                 if ( data.getType().equals("accelerometer") )
                 {
                     m_x_accelerometer.setText(String.valueOf(data.getX()));
                     m_y_accelerometer.setText(String.valueOf(data.getY()));
                     m_z_accelerometer.setText(String.valueOf(data.getZ()));
                 } else
                 {
                     m_x_gyroscope.setText(String.valueOf(data.getX()));
                     m_y_gyroscope.setText(String.valueOf(data.getY()));
                     m_z_gyroscope.setText(String.valueOf(data.getZ()));
                 }
             }
         };
     }
View it.braceletreader.fragments.MainFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Called when the view is created
Definition at line 89 of file MainFragment.java.
References it.braceletreader.SharedData.get(), it.braceletreader.BraceletReader.USER_IMAGE, and it.braceletreader.BraceletReader.USERNAME.
     {
         View view = super.onCreateView(inflater, container, savedInstanceState);
         /*
          * UI initialization
          */
         this.m_imageView = (ImageView) view.findViewById(R.id.imageview);
         this.m_imageView.setImageBitmap((Bitmap) this.m_sharedData.get(BraceletReader.USER_IMAGE));
         this.m_username = (TextView) view.findViewById(R.id.name_textview);
         this.m_username.setText((String) this.m_sharedData.get(BraceletReader.USERNAME));
         this.m_x_accelerometer = (TextView) view.findViewById(R.id.x_accelerometer_textview);
         this.m_y_accelerometer = (TextView) view.findViewById(R.id.y_accelerometer_textview);
         this.m_z_accelerometer = (TextView) view.findViewById(R.id.z_accelerometer_textview);
         this.m_x_gyroscope = (TextView) view.findViewById(R.id.x_gyroscope_textview);
         this.m_y_gyroscope = (TextView) view.findViewById(R.id.y_gyroscope_textview);
         this.m_z_gyroscope = (TextView) view.findViewById(R.id.z_gyroscope_textview);
         // Add to SharedData to get notifications
         this.m_sharedData.addObserver(this);
         return view;
     }
void it.braceletreader.fragments.MainFragment.onDestroyView ()
Called when the view is destroyed
Definition at line 117 of file MainFragment.java.
     {
         this.m_sharedData.deleteObserver(this);
         super.onDestroyView();
     }
void it.braceletreader.fragments.MainFragment.update (Observable observable, Object data)
Called when SharedData is modified
Definition at line 139 of file MainFragment.java.
References it.braceletreader.SharedData.get(), it.braceletreader.BraceletReader.USER_IMAGE, and it.braceletreader.BraceletReader.USERNAME.
     {
         this.m_imageView.setImageBitmap((Bitmap) this.m_sharedData.get(BraceletReader.USER_IMAGE));
         this.m_username.setText((String) this.m_sharedData.get(BraceletReader.USERNAME));
     }
void it.braceletreader.fragments.MainFragment.updateUI (Object data)
Update the UI
Parameters
data A JSON string
Definition at line 128 of file MainFragment.java.
Referenced by it.braceletreader.BraceletReader.updateUI().
     {
         Message message = this.m_handler.obtainMessage();
         message.obj = data;
         message.sendToTarget();
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/fragments/MainFragment.java