My Project: it.braceletreader.SharedData Class Reference
it.braceletreader.SharedData Class Reference
Public Member Functions
void put (String key, Object value)
Object get (String key)
void remove (String key)
Static Public Member Functions
static SharedData getInstance ()
Detailed Description
Class singleton created to contain shared data with a String key and an Object value
Author
Lucchetti Daniele
Definition at line 14 of file SharedData.java.
Member Function Documentation
Object it.braceletreader.SharedData.get (String key)
Return the value corresponding the specified key
Parameters
key The key
Returns
The object mapped with the specified key or null if it does not exist
Definition at line 47 of file SharedData.java.
Referenced by it.braceletreader.BraceletReader.notifyListenerStateChanged(), it.braceletreader.fragments.SettingFragment.onCreateView(), it.braceletreader.fragments.MainFragment.onCreateView(), it.braceletreader.BraceletReader.startWifiConnection(), and it.braceletreader.fragments.MainFragment.update().
     {
         return this.m_data.get(key);
     }
static SharedData it.braceletreader.SharedData.getInstance () static
Return the only instance of SharedData
Returns
The instance
Definition at line 70 of file SharedData.java.
Referenced by it.braceletreader.fragments.MainFragment.MainFragment(), it.braceletreader.BraceletReader.onCreate(), and it.braceletreader.fragments.SettingFragment.SettingFragment().
     {
         return m_instance;
     }
void it.braceletreader.SharedData.put (String key, Object value)
Map value in data structure with the specified key
Parameters
key The key
value The value
Definition at line 33 of file SharedData.java.
Referenced by it.braceletreader.BraceletReader.createBluetoothConnections(), it.braceletreader.BraceletReader.notifyListenerStateChanged(), it.braceletreader.fragments.SettingFragment.onCreateView(), and it.braceletreader.BraceletReader.setUserImage().
     {
         this.m_data.put(key, value);
         // Notify to Observers
         setChanged();
         notifyObservers();
     }
void it.braceletreader.SharedData.remove (String key)
Remove the object mapped with the specified key
Parameters
key The key of the object we want delete
Definition at line 57 of file SharedData.java.
     {
         this.m_data.remove(key);
         // Notify to Observers
         setChanged();
         notifyObservers();
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/SharedData.java