My Project: it.braceletreader.listeners.BraceletListener Class Reference
it.braceletreader.listeners.BraceletListener Class Reference abstract
Public Member Functions
BraceletListener (int id, BraceletReader braceletReader, DataManager< Data > dataManager, BluetoothDevice device)
void alt ()
BluetoothDevice getDevice ()
Static Public Attributes
static final int CONNECTION_ESTABLISHED = 0
The connection is established.
static final int ERROR_CREATING_CONNECTION = 1
Error when trying to connect.
static final int ERROR_STREAMING = 2
Error during the data streaming.
static final int ERROR_DATA_FORMAT = 3
Error of data format.
static final int ERROR_CLOSING_CONNECTION = 4
Error during closing connection.
Protected Attributes
int m_id
Id of the Thread.
BraceletReader m_braceletReader
Main class to communicate state changing.
DataManager< Data > m_dataManager
Data structure to put data receiving by bracelet.
BluetoothDevice m_device
Bluetooth device to receive data.
boolean m_stop
When is set true, the Thread die.
Detailed Description
Thread that connect to a single bracelet and receive data. Run method must be implemented
Author
Lucchetti Daniele
Definition at line 15 of file BraceletListener.java.
Constructor & Destructor Documentation
it.braceletreader.listeners.BraceletListener.BraceletListener (int id, BraceletReader braceletReader, DataManager< Data > dataManager, BluetoothDevice device)
Constructor
Parameters
id Thread id
braceletReader Main class
dataManager Data structure to put data
device Device to get data
Definition at line 37 of file BraceletListener.java.
     {
         this.m_id = id;
         this.m_braceletReader = braceletReader;
         this.m_dataManager = dataManager;
         this.m_device = device;
         this.m_stop = false;
     }
Member Function Documentation
void it.braceletreader.listeners.BraceletListener.alt ()
Stop the Thread
Definition at line 49 of file BraceletListener.java.
Referenced by it.braceletreader.BraceletReader.createBluetoothConnections(), it.braceletreader.BraceletReader.notifyListenerStateChanged(), and it.braceletreader.BraceletReader.onDestroy().
     {
         this.m_stop = true;
     }
BluetoothDevice it.braceletreader.listeners.BraceletListener.getDevice ()
Return the connected device
Returns
Connected device
Definition at line 59 of file BraceletListener.java.
References it.braceletreader.listeners.BraceletListener.m_device.
Referenced by it.braceletreader.BraceletReader.notifyListenerStateChanged().
     {
         return this.m_device;
     }
The documentation for this class was generated from the following file:
src/it/braceletreader/listeners/BraceletListener.java